# convertendo este comando abaixo em docker compose
# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker
# -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql

version: "3"

services:
  hr-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hrapi
# quem baixar nossa aplicação, agora é só usar
# docker compose up -d

# pra deletar o conteiner e apagar os dados:
# docker compose down

# pra apenas parar o conteiner sem deletar:
# docker compose stop
